name: Telegram Scheduler

on:
  schedule:
    - cron: "*/5 * * * *"   # каждые 5 минут
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install pymongo[srv] requests
      - env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
          MONGO_DB: telegram
          MONGO_COLL: tasks
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          PRUNE_DAYS_SENT: 30
          PRUNE_DAYS_ERROR: 60
        run: python runner.py
